export const DEFECTIVE_ITEMS = [
  { id: 'air_compressor', name: 'air_compressor', required: false },
  { id: 'air_lines', name: 'air_lines', required: false },
  { id: 'battery', name: 'battery', asterisk: true },
  { id: 'body', name: 'body', required: false },
  { id: 'brake_accessories', name: 'brake_accessories', required: false },
  { id: 'brakes', name: 'brakes', asterisk: true },
  { id: 'clutch', name: 'clutch', required: false },
  { id: 'defroster', name: 'defroster', required: false },
  { id: 'drive_line', name: 'drive_line', required: false },
  { id: 'engine', name: 'engine', asterisk: true },
  { id: 'fifth_wheel', name: 'fifth_wheel', required: false },
  { id: 'front_axle', name: 'front_axle', required: false },
  { id: 'fuel_tanks', name: 'fuel_tanks', asterisk: true },
  { id: 'generator', name: 'generator', required: false },
  { id: 'heater', name: 'heater', required: false },
  { id: 'horn', name: 'horn', required: false },
  { id: 'lights', name: 'lights', asterisk: true },
  { id: 'head', name: 'head', asterisk: true },
  { id: 'tail', name: 'tail', asterisk: true },
  { id: 'stop', name: 'stop', asterisk: true },
  { id: 'dash', name: 'dash', asterisk: true },
  { id: 'turn_indicators', name: 'turn_indicators', asterisk: true },
  { id: 'emergency_flasher', name: 'emergency_flasher', asterisk: true },
  { id: 'mirrors', name: 'mirrors', asterisk: true },
  { id: 'muffler_exhaust', name: 'muffler_exhaust', required: false },
  { id: 'oil_pressure', name: 'oil_pressure', asterisk: true },
  { id: 'placards', name: 'placards', required: false },
  { id: 'radiator', name: 'radiator', asterisk: true },
  { id: 'rear_end', name: 'rear_end', asterisk: true },
  { id: 'reflectors', name: 'reflectors', asterisk: true },
  { id: 'safety_equipment', name: 'safety_equipment', asterisk: true },
  { id: 'fire_extinguisher', name: 'fire_extinguisher', asterisk: true },
  { id: 'reflective_triangles', name: 'reflective_triangles', asterisk: true },
  { id: 'spare_bulbs', name: 'spare_bulbs', asterisk: true },
  { id: 'spare_fuses', name: 'spare_fuses', asterisk: true },
  { id: 'backup_alarm', name: 'backup_alarm', asterisk: true },
  { id: 'seat_belts', name: 'seat_belts', asterisk: true },
  { id: 'springs', name: 'springs', required: false },
  { id: 'starter', name: 'starter', required: false },
  { id: 'steering', name: 'steering', asterisk: true },
  { id: 'tachograph', name: 'tachograph', required: false },
  { id: 'wheels_lugnuts', name: 'wheels_lugnuts', asterisk: true },
  { id: 'transmission', name: 'transmission', required: false },
  { id: 'windows', name: 'windows', asterisk: true },
  { id: 'windshield_wipers', name: 'windshield_wipers', asterisk: true },
  { id: 'other', name: 'other', required: false }
];

export const TRUCK_TRAILER_ITEMS = [
  { id: 'brake_connections', name: 'brake_connections' },
  { id: 'brakes', name: 'brakes' },
  { id: 'coupling_chains', name: 'coupling_chains' },
  { id: 'coupling_king_pin', name: 'coupling_king_pin' },
  { id: 'doors', name: 'doors' },
  { id: 'hitch', name: 'hitch' },
  { id: 'landing_gear', name: 'landing_gear' },
  { id: 'lights_all', name: 'lights_all' },
  { id: 'placards', name: 'placards' },
  { id: 'reflectors', name: 'reflectors' },
  { id: 'roof', name: 'roof' },
  { id: 'springs', name: 'springs' },
  { id: 'tarpaulin', name: 'tarpaulin' },
  { id: 'tires', name: 'tires' },
  { id: 'wheels_lugnuts', name: 'wheels_lugnuts' },
  { id: 'other', name: 'other' }
];