export const DEFECTIVE_ITEMS = [
  { id: 'air_compressor', name: 'Air Compressor', required: false },
  { id: 'air_lines', name: 'Air Lines', required: false },
  { id: 'battery', name: 'Battery', asterisk: true },
  { id: 'body', name: 'Body', required: false },
  { id: 'brake_accessories', name: 'Brake Accessories', required: false },
  { id: 'brakes', name: 'Brakes', asterisk: true },
  { id: 'clutch', name: 'Clutch', required: false },
  { id: 'defroster', name: 'Defroster', required: false },
  { id: 'drive_line', name: 'Drive Line', required: false },
  { id: 'engine', name: 'Engine', asterisk: true },
  { id: 'fifth_wheel', name: 'Fifth Wheel', required: false },
  { id: 'front_axle', name: 'Front Axle', required: false },
  { id: 'fuel_tanks', name: 'Fuel Tanks', asterisk: true },
  { id: 'generator', name: 'Generator', required: false },
  { id: 'heater', name: 'Heater', required: false },
  { id: 'horn', name: 'Horn', required: false },
  { id: 'lights', name: 'Lights', asterisk: true },
  { id: 'head', name: 'Head', required: false },
  { id: 'tail', name: 'Tail', asterisk: true },
  { id: 'stop', name: 'Stop', asterisk: true },
  { id: 'dash', name: 'Dash', asterisk: true },
  { id: 'turn_indicators', name: 'Turn Indicators', asterisk: true },
  { id: 'emergency_flasher', name: 'Emergency Flasher', asterisk: true },
  { id: 'mirrors', name: 'Mirrors', asterisk: true },
  { id: 'muffler_exhaust', name: 'Muffler-Exhaust System', required: false },
  { id: 'oil_pressure', name: 'Oil Pressure', required: false },
  { id: 'placards', name: 'Placards', required: false },
  { id: 'radiator', name: 'Radiator', asterisk: true },
  { id: 'rear_end', name: 'Rear End', required: false },
  { id: 'reflectors', name: 'Reflectors', asterisk: true },
  { id: 'safety_equipment', name: 'Safety Equipment', asterisk: true },
  { id: 'fire_extinguisher', name: 'Fire Extinguisher', required: false },
  { id: 'reflective_triangles', name: 'Reflective Triangles', required: false },
  { id: 'spare_bulbs', name: 'Spare Bulbs', required: false },
  { id: 'spare_fuses', name: 'Spare Fuses', required: false },
  { id: 'backup_alarm', name: 'Back-up Alarm', required: false },
  { id: 'seat_belts', name: 'Seat Belts', asterisk: true },
  { id: 'springs', name: 'Springs', required: false },
  { id: 'starter', name: 'Starter', required: false },
  { id: 'steering', name: 'Steering', asterisk: true },
  { id: 'tachograph', name: 'Tachograph', required: false },
  { id: 'wheels_lugnuts', name: 'Wheels and Lugnuts', asterisk: true },
  { id: 'transmission', name: 'Transmission', required: false },
  { id: 'windows', name: 'Windows', asterisk: true },
  { id: 'windshield_wipers', name: 'Windshield Wipers', asterisk: true },
  { id: 'other', name: 'Other', required: false }
];

export const TRUCK_TRAILER_ITEMS = [
  { id: 'brake_connections', name: 'Brake Connections' },
  { id: 'brakes', name: 'Brakes' },
  { id: 'coupling_chains', name: 'Coupling Chains' },
  { id: 'coupling_king_pin', name: 'Coupling (King) Pin' },
  { id: 'doors', name: 'Doors' },
  { id: 'hitch', name: 'Hitch' },
  { id: 'landing_gear', name: 'Landing Gear' },
  { id: 'lights_all', name: 'Lights - All' },
  { id: 'placards', name: 'Placards' },
  { id: 'reflectors', name: 'Reflectors' },
  { id: 'roof', name: 'Roof' },
  { id: 'springs', name: 'Springs' },
  { id: 'tarpaulin', name: 'Tarpaulin' },
  { id: 'tires', name: 'Tires' },
  { id: 'wheels_lugnuts', name: 'Wheels and Lugnuts' },
  { id: 'other', name: 'Other' }
];